-- 015 – trilha de auditoria (ISO 27001 A.8.15 / LGPD art. 37). O backend grava aqui toda
-- criação, alteração e exclusão feita pelo EF, além de logins, recuperação de senha e pedidos
-- LGPD. A tabela é append-only: UPDATE é recusado pelo banco; DELETE só pela rotina de
-- retenção (RetencaoDadosService). Aplique ANTES do deploy do backend: sem a tabela, toda
-- gravação falha, porque o registro de auditoria vai na mesma transação do dado.

BEGIN;

-- 0) Controle de execução
CREATE TABLE IF NOT EXISTS "MigracoesAplicadas" (
    "Nome"       TEXT        PRIMARY KEY,
    "AplicadaEm" TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo')
);

-- 1) Tabela. Sem FK para "Usuarios" de propósito: a trilha sobrevive à anonimização do titular.
CREATE TABLE IF NOT EXISTS "LogsAuditoria" (
    "IdLog"        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OcorridoEm"   TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo'),
    "IdUsuario"    UUID          NULL,
    "Papel"        VARCHAR(20)   NULL,
    "Acao"         VARCHAR(60)   NOT NULL,
    "Entidade"     VARCHAR(60)   NOT NULL,
    "IdEntidade"   VARCHAR(64)   NULL,
    "Detalhes"     TEXT          NULL,
    "Sucesso"      BOOLEAN       NOT NULL DEFAULT TRUE,
    "Ip"           VARCHAR(45)   NULL,
    "UserAgent"    VARCHAR(300)  NULL,
    "IdCorrelacao" VARCHAR(64)   NULL
);

CREATE INDEX IF NOT EXISTS "IX_LogsAuditoria_OcorridoEm"
    ON "LogsAuditoria" ("OcorridoEm");
CREATE INDEX IF NOT EXISTS "IX_LogsAuditoria_IdUsuario_OcorridoEm"
    ON "LogsAuditoria" ("IdUsuario", "OcorridoEm");
CREATE INDEX IF NOT EXISTS "IX_LogsAuditoria_Entidade_IdEntidade"
    ON "LogsAuditoria" ("Entidade", "IdEntidade");

-- 2) Imutabilidade: registro de auditoria não se corrige, só se acrescenta.
CREATE OR REPLACE FUNCTION "fn_logs_auditoria_imutavel"() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'LogsAuditoria é somente inclusão: UPDATE não é permitido.';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "trg_logs_auditoria_imutavel" ON "LogsAuditoria";
CREATE TRIGGER "trg_logs_auditoria_imutavel"
    BEFORE UPDATE ON "LogsAuditoria"
    FOR EACH ROW EXECUTE FUNCTION "fn_logs_auditoria_imutavel"();

-- 3) Mesmo tratamento das demais tabelas (ver 010): nada exposto pela API REST do Supabase.
ALTER TABLE "public"."LogsAuditoria" ENABLE ROW LEVEL SECURITY;

-- 4) Códigos de recuperação: índice para a busca por e-mail que invalida os códigos anteriores.
CREATE INDEX IF NOT EXISTS "IX_CodigosRedefinicaoSenha_Email_Usado"
    ON "CodigosRedefinicaoSenha" ("Email", "Usado");

INSERT INTO "MigracoesAplicadas" ("Nome") VALUES ('015_auditoria')
ON CONFLICT ("Nome") DO NOTHING;

-- 5) Conferência
SELECT COUNT(*) AS "LogsAuditoria" FROM "LogsAuditoria";

COMMIT;
